services:
  frontend:
    image: ghcr.io/nakakonakako/receipt-manager-frontend:latest
    container_name: receipt-frontend
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - receipt-backend

  receipt-backend:
    image: ghcr.io/nakakonakako/receipt-manager-backend:latest
    container_name: receipt-backend
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - ./service_account.json:/app/service_account.json
  
volumes:
  https-portal-data: