services:
  web:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "receipt.avantgardechan.com -> http://frontend:80"
      STAGE: "production"
      CLIENT_MAX_BODY_SIZE: 20M
    volumes:
      - https-portal-data:/var/lib/https-portal

  frontend:
    image: ghcr.io/nakakonakako/receipt-manager-frontend:latest
    container_name: receipt-frontend
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - receipt-backend

  receipt-backend:
    image: ghcr.io/nakakonakako/receipt-manager-backend:latest
    container_name: receipt-backend
    expose:
      - "8000"
    env_file:
      - ./.env
    volumes:
      - ./services_account.json:/app/services_account.json
  
volumes:
  https-portal-data: