services:
  frontend:
    image: ghcr.io/nakakonakako/receipt-manager-frontend:latest
    container_name: receipt-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - receipt-backend

  receipt-backend:
    image: ghcr.io/nakakonakako/receipt-manager-backend:latest
    container_name: receipt-backend
    expose:
      - "8000"
    env_file:
      - ./.env
